apiVersion: v1
kind: Service
metadata:
  name: spring-consumer-service
  namespace: project
spec:
  selector:
    app: spring-consumer
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-consumer
  namespace: project
spec:
  selector:
    matchLabels:
      app: spring-consumer
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-consumer
    spec:
      containers:
        - name: spring-consumer
          image: mertcakmak2/spring-rabbit-consumer
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: JAEGER_HOST
              value: "jaeger-collector"